kind: Deployment
apiVersion: apps/v1
metadata:
  name: csi-gce-pd-controller
  annotations:
    # https://kubernetes.io/docs/tutorials/clusters/apparmor/
    container.apparmor.security.beta.kubernetes.io/gce-pd-driver: unconfined
spec:
  template:
    spec:
      containers:
        - name: gce-pd-driver
          imagePullPolicy: Always
          command: ["/go/bin/dlv"]
          args:
            - "--listen=:2345"
            - "--headless=true"
            - "--api-version=2"
            # https://github.com/go-delve/delve/blob/master/Documentation/usage/dlv_exec.md#options
            - "--accept-multiclient"
            - "--continue"
            - "--log"
            - "exec"
            - "/go/src/sigs.k8s.io/gcp-compute-persistent-disk-csi-driver/bin/gce-pd-csi-driver"
            - "--"
            - "--v=5"
            - "--endpoint=unix:/csi/csi.sock"
          ports:
            - containerPort: 2345
          securityContext:
            capabilities:
              add:
              - SYS_PTRACE

